apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: produtos-api
  template:
    metadata:
      labels:
        app: produtos-api
    spec:
      containers:
        - name: produtos-api
          image: sergiocoti/produtos-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: produtos-db-secret
                  key: DATABASE_URL